In [86]:
import pandas as pd
df = pd.read_csv("../data/features.csv")
print(df.shape)
display(df.head())

swindon_names = pd.read_excel("../data/Swindon LSOA local names.xlsx")
df_swindon = df[df["LSOA21CD"].isin(swindon_names["LSOA21CD"])].copy()
print(df_swindon.shape)
print(df_swindon["MSOA21CD"].nunique())

(1129, 83)

,LSOA21CD,LSOA21NM,LSOA21NMW,RUC21CD,RUC21NM,Urban_rura,Shape_Leng,Shape__Are,Shape__Len,MSOA21CD,...,share_enterprises_industrial_2025_msoa,share_enterprises_kibs_2025_msoa,share_enterprises_anchor_2025_msoa,enterprises_per_1k_residents_2025,share_enterprises_public_2025_msoa,share_enterprises_private_2025_msoa,bus_stop_count,area_km2,bus_stop_density,dist_to_primary_m
0,E01015471,Swindon 028A,NaN,UN1,Urban: Nearer to a major town or city,Urban,4013.589687,5.013996e+05,4013.589687,E02006849,...,0.020833,0.458333,0.083333,105.448155,0.000000,1.000000,5,1.298791,3.849735,617.714131
1,E01015473,Swindon 008A,NaN,RSN1,Smaller rural: Nearer to a major town or city,Rural,25688.031740,1.524397e+07,25688.031738,E02003219,...,0.045752,0.405229,0.065359,351.401011,0.006536,0.993464,37,39.476058,0.937277,574.697536
2,E01015475,Swindon 015A,NaN,UN1,Urban: Nearer to a major town or city,Urban,2099.250451,2.145225e+05,2099.250451,E02003226,...,0.016129,0.290323,0.064516,124.298316,0.000000,1.000000,10,0.554698,18.027840,350.510113
3,E01015477,Swindon 015C,NaN,UN1,Urban: Nearer to a major town or city,Urban,3276.800336,2.405209e+05,3276.800336,E02003226,...,0.016129,0.290323,0.064516,171.365395,0.000000,1.000000,5,0.621788,8.041327,473.126804
4,E01015478,Swindon 021A,NaN,UN1,Urban: Nearer to a major town or city,Urban,4188.002606,6.194380e+05,4188.002606,E02003232,...,0.033898,0.406780,0.067797,181.315304,0.000000,1.000000,6,1.601008,3.747640,58.398219

(140, 83)
27

In [87]:
msoa_check = (df_swindon.groupby(["MSOA21CD", "MSOA21NM"]).size().reset_index(name="Number of LSOAs"))
display(msoa_check)
print("Number of MSOAs:", len(msoa_check))
print("Total number of LSOAs:", msoa_check["Number of LSOAs"].sum())

     MSOA21CD     MSOA21NM  Number of LSOAs
0   E02003212  Swindon 001                6
1   E02003214  Swindon 003                4
2   E02003215  Swindon 004                5
3   E02003216  Swindon 005                6
4   E02003217  Swindon 006                4
5   E02003218  Swindon 007                4
6   E02003219  Swindon 008                8
7   E02003220  Swindon 009                6
8   E02003221  Swindon 010                4
9   E02003222  Swindon 011                4
10  E02003223  Swindon 012                6
11  E02003224  Swindon 013                6
12  E02003225  Swindon 014                4
13  E02003226  Swindon 015                5
14  E02003227  Swindon 016                3
15  E02003228  Swindon 017                4
16  E02003229  Swindon 018                4
17  E02003230  Swindon 019                5
18  E02003231  Swindon 020                6
19  E02003232  Swindon 021                5
20  E02003233  Swindon 022                6
21  E02003234  Swindon 023                6
22  E02003235  Swindon 024                5
23  E02003236  Swindon 025                7
24  E02006847  Swindon 026                6
25  E02006848  Swindon 027                5
26  E02006849  Swindon 028                6

Number of MSOAs: 27
Total number of LSOAs: 140

In [88]:
for col in df_swindon.columns:
    print(col)

LSOA21CD
LSOA21NM
LSOA21NMW
RUC21CD
RUC21NM
Urban_rura
Shape_Leng
Shape__Are
Shape__Len
MSOA21CD
MSOA21NM
VOA_hereditaments_2023
VOA_total_RV_2023
VOA_median_RV_2023
VOA_total_RV_million_2023
VOA_median_RV_thousand_2023
VOA_hereditaments_2026
VOA_total_RV_2026
VOA_median_RV_2026
VOA_total_RV_million_2026
VOA_median_RV_thousand_2026
VOA_total_RV_pct_change
Mid-2024 population
Apprenticeship %
Level 1 and entry level qualifications: 1 to 4 GCSEs grade A* to C, Any GCSEs at other grades, O levels or CSEs (any grades), 1 AS level, NVQ level 1, Foundation GNVQ, Basic or Essential Skills %
Level 2 qualifications: 5 or more GCSEs (A* to C or 9 to 4), O levels (passes), CSEs (grade 1), School Certification, 1 A level, 2 to 3 AS levels, VCEs, Intermediate or Higher Diploma, Welsh Baccalaureate Intermediate Diploma, NVQ level 2, Intermediate GNVQ, City and Guilds Craft, BTEC First or General Diploma, RSA Diploma %
Level 3 qualifications: 2 or more A levels or VCEs, 4 or more AS levels, Higher School Certificate, Progression or Advanced Diploma, Welsh Baccalaureate Advance Diploma, NVQ level 3; Advanced GNVQ, City and Guilds Advanced Craft, ONC, OND, BTEC National, RSA Advanced Diploma %
Level 4 qualifications or above: degree (BA, BSc), higher degree (MA, PhD, PGCE), NVQ level 4 to 5, HNC, HND, RSA Higher Diploma, BTEC Higher level, professional qualifications (for example, teaching, nursing, accountancy) %
No qualifications %
Other: vocational or work-related qualifications, other qualifications achieved in England or Wales, qualifications achieved outside England or Wales (equivalent not stated or unknown) %
IMD_decile
Income_decile
Employment_decile
Education_decile
AdultSkills_decile
Pct_Working_Age
Working_Age_Pop
Total_Pop_Mid2024
Percentage of connections receiving less than 10Mbit/s broadband
Average download speed (Mbit/s)
Percentage of homes unable to receive at least 30Mbit/s broadband
LSOA GVA Estimates (millions)
LSOA11CD
part_time_employees
full_time_employees
full_to_part_ratio
total_employees
employment_rate_per_pop
LU_large_2025_msoa
LU_medium_2025_msoa
LU_micro_2025_msoa
LU_small_2025_msoa
LU_total_2025_msoa
LU_pct_micro_2025_msoa
LU_pct_small_2025_msoa
LU_pct_medium_2025_msoa
LU_pct_large_2025_msoa
LU_diversity_1-HHI_2025
pct_enterprise_0_to_49_thousand_2025_msoa
pct_enterprise_100_to_249_thousand_2025_msoa
pct_enterprise_1000_to_1999_thousand_2025_msoa
pct_enterprise_10000_to_49999_thousand_2025_msoa
pct_enterprise_2000_to_4999_thousand_2025_msoa
pct_enterprise_250_to_499_thousand_2025_msoa
pct_enterprise_50_to_99_thousand_2025_msoa
pct_enterprise_500_to_999_thousand_2025_msoa
pct_enterprise_5000_to_9999_thousand_2025_msoa
pct_enterprise_50000plus_thousand_2025_msoa
turnover_diversity_1-HHI_2025_msoa
total_enterprises_2025_msoa
share_enterprises_creative_2025_msoa
share_enterprises_foundational_2025_msoa
share_enterprises_green_aligned_2025_msoa
share_enterprises_industrial_2025_msoa
share_enterprises_kibs_2025_msoa
share_enterprises_anchor_2025_msoa
enterprises_per_1k_residents_2025
share_enterprises_public_2025_msoa
share_enterprises_private_2025_msoa
bus_stop_count
area_km2
bus_stop_density
dist_to_primary_m

In [89]:
sum_columns = [
    "LSOA GVA Estimates (millions)",
    "Mid-2024 population",
    "Working_Age_Pop",
    "Total_Pop_Mid2024",
    "part_time_employees",
    "full_time_employees",
    "total_employees",
    "bus_stop_count",
    "area_km2"
]

print(df_swindon[sum_columns].dtypes)
print("\nMissing values:")
print(df_swindon[sum_columns].isnull().sum())

LSOA GVA Estimates (millions)    float64
Mid-2024 population                int64
Working_Age_Pop                    int64
Total_Pop_Mid2024                  int64
part_time_employees                int64
full_time_employees                int64
total_employees                    int64
bus_stop_count                     int64
area_km2                         float64
dtype: object

Missing values:
LSOA GVA Estimates (millions)    13
Mid-2024 population               0
Working_Age_Pop                   0
Total_Pop_Mid2024                 0
part_time_employees               0
full_time_employees               0
total_employees                   0
bus_stop_count                    0
area_km2                          0
dtype: int64

In [90]:
gva_missing = df_swindon[
    df_swindon["LSOA GVA Estimates (millions)"].isnull()
][
    ["LSOA21CD", "LSOA21NM", "MSOA21CD", "MSOA21NM"]
]

display(gva_missing)
print("\nNumber of MSOAs:", gva_missing["MSOA21CD"].nunique())

       LSOA21CD      LSOA21NM   MSOA21CD     MSOA21NM
1026  E01033840  Swindon 008E  E02003219  Swindon 008
1027  E01033841  Swindon 008F  E02003219  Swindon 008
1028  E01033842  Swindon 008G  E02003219  Swindon 008
1029  E01033843  Swindon 008H  E02003219  Swindon 008
1030  E01033844  Swindon 008I  E02003219  Swindon 008
1031  E01033845  Swindon 015E  E02003226  Swindon 015
1032  E01033846  Swindon 015F  E02003226  Swindon 015
1033  E01033847  Swindon 024E  E02003235  Swindon 024
1034  E01033848  Swindon 024F  E02003235  Swindon 024
1035  E01033849  Swindon 025G  E02003236  Swindon 025
1036  E01033850  Swindon 025H  E02003236  Swindon 025
1047  E01033860  Swindon 028F  E02006849  Swindon 028
1048  E01033861  Swindon 028G  E02006849  Swindon 028

Number of MSOAs: 5

In [91]:
gva_missing_by_msoa = (gva_missing.groupby(["MSOA21CD", "MSOA21NM"]).size().reset_index(name="Missing GVA LSOAs"))
display(gva_missing_by_msoa)

    MSOA21CD     MSOA21NM  Missing GVA LSOAs
0  E02003219  Swindon 008                  5
1  E02003226  Swindon 015                  2
2  E02003235  Swindon 024                  2
3  E02003236  Swindon 025                  2
4  E02006849  Swindon 028                  2

In [92]:
msoa_features = (
    df_swindon
    .groupby(
        ["MSOA21CD", "MSOA21NM"],
        as_index=False
    )
    .agg({
        "LSOA GVA Estimates (millions)": "sum",
        "Mid-2024 population": "sum",
        "Working_Age_Pop": "sum",
        "Total_Pop_Mid2024": "sum",
        "part_time_employees": "sum",
        "full_time_employees": "sum",
        "total_employees": "sum",
        "bus_stop_count": "sum",
        "area_km2": "sum"
    })
)

missing_gva_msoa = df_swindon[
    df_swindon["LSOA GVA Estimates (millions)"].isna()
]["MSOA21CD"].unique()

msoa_features.loc[
    msoa_features["MSOA21CD"].isin(missing_gva_msoa),
    "LSOA GVA Estimates (millions)"
] = np.nan

display(msoa_features)

,MSOA21CD,MSOA21NM,LSOA GVA Estimates (millions),Mid-2024 population,Working_Age_Pop,Total_Pop_Mid2024,part_time_employees,full_time_employees,total_employees,bus_stop_count,area_km2
0,E02003212,Swindon 001,190.346,8447,4951,8447,895,550,1445,30,79.681517
1,E02003214,Swindon 003,33.945,6970,4295,6970,165,100,265,18,3.844477
2,E02003215,Swindon 004,52.529,6768,4029,6768,355,420,775,33,3.966716
3,E02003216,Swindon 005,101.160,9974,6224,9974,860,575,1435,48,7.790981
4,E02003217,Swindon 006,53.666,7661,4910,7661,400,345,745,19,3.360773
5,E02003218,Swindon 007,60.336,6576,4198,6576,455,200,655,29,3.475176
6,E02003219,Swindon 008,NaN,15406,9926,15406,13975,5800,19775,106,254.128578
7,E02003220,Swindon 009,1170.527,10981,6918,10981,4350,1500,5850,57,14.343444
8,E02003221,Swindon 010,760.038,7617,5252,7617,3975,1485,5460,28,5.222763
9,E02003222,Swindon 011,55.019,5905,4079,5905,325,315,640,26,4.150600
10,E02003223,Swindon 012,768.559,11663,8224,11663,12850,3525,16375,47,12.544078
11,E02003224,Swindon 013,200.970,8635,5282,8635,795,260,1055,35,4.689733
12,E02003225,Swindon 014,1060.761,6539,4396,6539,9725,2175,11900,43,7.684564
13,E02003226,Swindon 015,NaN,10907,8103,10907,4475,1375,5850,44,2.494710
14,E02003227,Swindon 016,79.185,5126,3394,5126,625,355,980,23,2.093782
15,E02003228,Swindon 017,294.453,7992,5289,7992,3025,1600,4625,34,5.066148
16,E02003229,Swindon 018,52.551,5468,3832,5468,285,170,455,18,5.088828
17,E02003230,Swindon 019,259.206,10310,7686,10310,3750,2750,6500,25,2.419894
18,E02003231,Swindon 020,68.176,10783,7065,10783,430,270,700,33,4.390731
19,E02003232,Swindon 021,277.969,8829,6099,8829,1140,720,1860,36,5.852689
20,E02003233,Swindon 022,3888.048,8667,5454,8667,6420,1620,8040,40,6.481744
21,E02003234,Swindon 023,342.344,8443,5233,8443,4570,1420,5990,35,7.681577
22,E02003235,Swindon 024,NaN,9940,6262,9940,1900,900,2800,44,14.238794
23,E02003236,Swindon 025,NaN,14527,8876,14527,1935,1650,3585,104,117.935703
24,E02006847,Swindon 026,62.192,10257,7185,10257,485,435,920,22,6.549983
25,E02006848,Swindon 027,66.568,8845,6334,8845,445,280,725,23,2.839258
26,E02006849,Swindon 028,NaN,10639,7365,10639,1550,1570,3120,30,7.108496

In [93]:
print("MSOA rows:", len(msoa_features))
print("Unique MSOAs:",msoa_features["MSOA21CD"].nunique())
print("Missing MSOA GVA:",msoa_features["LSOA GVA Estimates (millions)"].isnull().sum())

MSOA rows: 27
Unique MSOAs: 27
Missing MSOA GVA: 5

In [94]:
check_columns = [
    "Mid-2024 population",
    "Working_Age_Pop",
    "Total_Pop_Mid2024",
    "part_time_employees",
    "full_time_employees",
    "total_employees",
    "bus_stop_count",
    "area_km2"
]

for col in check_columns:
    before = df_swindon[col].sum()
    after = msoa_features[col].sum()

    print(col)
    print("Before:", before)
    print("After:", after)
    print("Same:", round(before, 6) == round(after, 6))

Mid-2024 population
Before: 243875
After: 243875
Same: True
Working_Age_Pop
Before: 160861
After: 160861
Same: True
Total_Pop_Mid2024
Before: 243875
After: 243875
Same: True
part_time_employees
Before: 80160
After: 80160
Same: True
full_time_employees
Before: 32365
After: 32365
Same: True
total_employees
Before: 112525
After: 112525
Same: True
bus_stop_count
Before: 1030
After: 1030
Same: True
area_km2
Before: 595.1257378162413
After: 595.1257378162413
Same: True

In [95]:
print((df_swindon["Mid-2024 population"]== df_swindon["Total_Pop_Mid2024"]).all())

True

In [96]:
msoa_columns = [
    "LU_large_2025_msoa",
    "LU_medium_2025_msoa",
    "LU_micro_2025_msoa",
    "LU_small_2025_msoa",
    "LU_total_2025_msoa",
    "LU_pct_micro_2025_msoa",
    "LU_pct_small_2025_msoa",
    "LU_pct_medium_2025_msoa",
    "LU_pct_large_2025_msoa"
]

for col in msoa_columns:
    max_values = df_swindon.groupby("MSOA21CD")[col].nunique().max()
    print(col, max_values)

LU_large_2025_msoa 1
LU_medium_2025_msoa 1
LU_micro_2025_msoa 1
LU_small_2025_msoa 1
LU_total_2025_msoa 1
LU_pct_micro_2025_msoa 1
LU_pct_small_2025_msoa 1
LU_pct_medium_2025_msoa 1
LU_pct_large_2025_msoa 1

In [97]:
msoa_business = (df_swindon.groupby(["MSOA21CD", "MSOA21NM"], as_index=False)[msoa_columns].first())
display(msoa_business.head())

,MSOA21CD,MSOA21NM,LU_large_2025_msoa,LU_medium_2025_msoa,LU_micro_2025_msoa,LU_small_2025_msoa,LU_total_2025_msoa,LU_pct_micro_2025_msoa,LU_pct_small_2025_msoa,LU_pct_medium_2025_msoa,LU_pct_large_2025_msoa
0,E02003212,Swindon 001,0,0,275,35,310,0.887097,0.112903,0.000000,0.0
1,E02003214,Swindon 003,0,0,75,5,80,0.937500,0.062500,0.000000,0.0
2,E02003215,Swindon 004,0,5,120,10,135,0.888889,0.074074,0.037037,0.0
3,E02003216,Swindon 005,0,5,210,30,245,0.857143,0.122449,0.020408,0.0
4,E02003217,Swindon 006,0,0,140,10,150,0.933333,0.066667,0.000000,0.0

In [98]:
msoa_features = msoa_features.merge(msoa_business, on=["MSOA21CD", "MSOA21NM"], how="left")
print(msoa_features.shape)
display(msoa_features.head())

(27, 20)

,MSOA21CD,MSOA21NM,LSOA GVA Estimates (millions),Mid-2024 population,Working_Age_Pop,Total_Pop_Mid2024,part_time_employees,full_time_employees,total_employees,bus_stop_count,area_km2,LU_large_2025_msoa,LU_medium_2025_msoa,LU_micro_2025_msoa,LU_small_2025_msoa,LU_total_2025_msoa,LU_pct_micro_2025_msoa,LU_pct_small_2025_msoa,LU_pct_medium_2025_msoa,LU_pct_large_2025_msoa
0,E02003212,Swindon 001,190.346,8447,4951,8447,895,550,1445,30,79.681517,0,0,275,35,310,0.887097,0.112903,0.000000,0.0
1,E02003214,Swindon 003,33.945,6970,4295,6970,165,100,265,18,3.844477,0,0,75,5,80,0.937500,0.062500,0.000000,0.0
2,E02003215,Swindon 004,52.529,6768,4029,6768,355,420,775,33,3.966716,0,5,120,10,135,0.888889,0.074074,0.037037,0.0
3,E02003216,Swindon 005,101.160,9974,6224,9974,860,575,1435,48,7.790981,0,5,210,30,245,0.857143,0.122449,0.020408,0.0
4,E02003217,Swindon 006,53.666,7661,4910,7661,400,345,745,19,3.360773,0,0,140,10,150,0.933333,0.066667,0.000000,0.0

In [99]:
other_msoa_columns = [
    "LU_diversity_1-HHI_2025",
    "pct_enterprise_0_to_49_thousand_2025_msoa",
    "pct_enterprise_100_to_249_thousand_2025_msoa",
    "pct_enterprise_1000_to_1999_thousand_2025_msoa",
    "pct_enterprise_10000_to_49999_thousand_2025_msoa",
    "pct_enterprise_2000_to_4999_thousand_2025_msoa",
    "pct_enterprise_250_to_499_thousand_2025_msoa",
    "pct_enterprise_50_to_99_thousand_2025_msoa",
    "pct_enterprise_500_to_999_thousand_2025_msoa",
    "pct_enterprise_5000_to_9999_thousand_2025_msoa",
    "pct_enterprise_50000plus_thousand_2025_msoa",
    "turnover_diversity_1-HHI_2025_msoa",
    "total_enterprises_2025_msoa",
    "share_enterprises_creative_2025_msoa",
    "share_enterprises_foundational_2025_msoa",
    "share_enterprises_green_aligned_2025_msoa",
    "share_enterprises_industrial_2025_msoa",
    "share_enterprises_kibs_2025_msoa",
    "share_enterprises_anchor_2025_msoa",
#    "enterprises_per_1k_residents_2025",
    "share_enterprises_public_2025_msoa",
    "share_enterprises_private_2025_msoa"
]

for col in other_msoa_columns:
    max_values = df_swindon.groupby("MSOA21CD")[col].nunique().max()
    print(col, max_values)

LU_diversity_1-HHI_2025 1
pct_enterprise_0_to_49_thousand_2025_msoa 1
pct_enterprise_100_to_249_thousand_2025_msoa 1
pct_enterprise_1000_to_1999_thousand_2025_msoa 1
pct_enterprise_10000_to_49999_thousand_2025_msoa 1
pct_enterprise_2000_to_4999_thousand_2025_msoa 1
pct_enterprise_250_to_499_thousand_2025_msoa 1
pct_enterprise_50_to_99_thousand_2025_msoa 1
pct_enterprise_500_to_999_thousand_2025_msoa 1
pct_enterprise_5000_to_9999_thousand_2025_msoa 1
pct_enterprise_50000plus_thousand_2025_msoa 1
turnover_diversity_1-HHI_2025_msoa 1
total_enterprises_2025_msoa 1
share_enterprises_creative_2025_msoa 1
share_enterprises_foundational_2025_msoa 1
share_enterprises_green_aligned_2025_msoa 1
share_enterprises_industrial_2025_msoa 1
share_enterprises_kibs_2025_msoa 1
share_enterprises_anchor_2025_msoa 1
share_enterprises_public_2025_msoa 1
share_enterprises_private_2025_msoa 1

In [100]:
other_msoa_data = (df_swindon.groupby(["MSOA21CD", "MSOA21NM"], as_index=False)[other_msoa_columns].first())
msoa_features = msoa_features.merge(other_msoa_data, on=["MSOA21CD", "MSOA21NM"],how="left")

msoa_features["enterprises_per_1k_residents_2025"] = (
    msoa_features["total_enterprises_2025_msoa"]
    / msoa_features["Total_Pop_Mid2024"]
    * 1000
)

print(msoa_features.shape)
display(msoa_features.head())

(27, 42)

,MSOA21CD,MSOA21NM,LSOA GVA Estimates (millions),Mid-2024 population,Working_Age_Pop,Total_Pop_Mid2024,part_time_employees,full_time_employees,total_employees,bus_stop_count,...,total_enterprises_2025_msoa,share_enterprises_creative_2025_msoa,share_enterprises_foundational_2025_msoa,share_enterprises_green_aligned_2025_msoa,share_enterprises_industrial_2025_msoa,share_enterprises_kibs_2025_msoa,share_enterprises_anchor_2025_msoa,share_enterprises_public_2025_msoa,share_enterprises_private_2025_msoa,enterprises_per_1k_residents_2025
0,E02003212,Swindon 001,190.346,8447,4951,8447,895,550,1445,30,...,270,0.092593,0.407407,0.018519,0.018519,0.370370,0.037037,0.0,1.0,31.964011
1,E02003214,Swindon 003,33.945,6970,4295,6970,165,100,265,18,...,60,0.083333,0.666667,0.083333,0.083333,0.250000,0.000000,0.0,1.0,8.608321
2,E02003215,Swindon 004,52.529,6768,4029,6768,355,420,775,33,...,115,0.043478,0.608696,0.000000,0.000000,0.304348,0.043478,0.0,1.0,16.991726
3,E02003216,Swindon 005,101.160,9974,6224,9974,860,575,1435,48,...,215,0.069767,0.534884,0.069767,0.069767,0.255814,0.093023,0.0,1.0,21.556046
4,E02003217,Swindon 006,53.666,7661,4910,7661,400,345,745,19,...,120,0.083333,0.625000,0.000000,0.000000,0.250000,0.041667,0.0,1.0,15.663751

In [101]:
msoa_features["bus_stop_density"] = (msoa_features["bus_stop_count"] / msoa_features["area_km2"])
display(msoa_features[["MSOA21CD", "MSOA21NM", "bus_stop_count", "area_km2", "bus_stop_density"]].head())

    MSOA21CD     MSOA21NM  bus_stop_count   area_km2  bus_stop_density
0  E02003212  Swindon 001              30  79.681517          0.376499
1  E02003214  Swindon 003              18   3.844477          4.682041
2  E02003215  Swindon 004              33   3.966716          8.319223
3  E02003216  Swindon 005              48   7.790981          6.160970
4  E02003217  Swindon 006              19   3.360773          5.653462

In [102]:
msoa_features["employment_rate_per_pop"] = (
    msoa_features["total_employees"]
    / msoa_features["Total_Pop_Mid2024"]
)

display(
    msoa_features[
        ["MSOA21CD", "MSOA21NM", "total_employees",
         "Total_Pop_Mid2024", "employment_rate_per_pop"]
    ].head()
)

,MSOA21CD,MSOA21NM,total_employees,Total_Pop_Mid2024,employment_rate_per_pop
0,E02003212,Swindon 001,1445,8447,0.171067
1,E02003214,Swindon 003,265,6970,0.038020
2,E02003215,Swindon 004,775,6768,0.114509
3,E02003216,Swindon 005,1435,9974,0.143874
4,E02003217,Swindon 006,745,7661,0.097246

In [103]:
msoa_features = msoa_features.drop(columns=["Mid-2024 population"])
msoa_features = msoa_features.rename(columns={"LSOA GVA Estimates (millions)": "MSOA GVA Estimates (millions)"})

print(msoa_features.shape)
display(msoa_features.head())

(27, 43)

,MSOA21CD,MSOA21NM,MSOA GVA Estimates (millions),Working_Age_Pop,Total_Pop_Mid2024,part_time_employees,full_time_employees,total_employees,bus_stop_count,area_km2,...,share_enterprises_foundational_2025_msoa,share_enterprises_green_aligned_2025_msoa,share_enterprises_industrial_2025_msoa,share_enterprises_kibs_2025_msoa,share_enterprises_anchor_2025_msoa,share_enterprises_public_2025_msoa,share_enterprises_private_2025_msoa,enterprises_per_1k_residents_2025,bus_stop_density,employment_rate_per_pop
0,E02003212,Swindon 001,190.346,4951,8447,895,550,1445,30,79.681517,...,0.407407,0.018519,0.018519,0.370370,0.037037,0.0,1.0,31.964011,0.376499,0.171067
1,E02003214,Swindon 003,33.945,4295,6970,165,100,265,18,3.844477,...,0.666667,0.083333,0.083333,0.250000,0.000000,0.0,1.0,8.608321,4.682041,0.038020
2,E02003215,Swindon 004,52.529,4029,6768,355,420,775,33,3.966716,...,0.608696,0.000000,0.000000,0.304348,0.043478,0.0,1.0,16.991726,8.319223,0.114509
3,E02003216,Swindon 005,101.160,6224,9974,860,575,1435,48,7.790981,...,0.534884,0.069767,0.069767,0.255814,0.093023,0.0,1.0,21.556046,6.160970,0.143874
4,E02003217,Swindon 006,53.666,4910,7661,400,345,745,19,3.360773,...,0.625000,0.000000,0.000000,0.250000,0.041667,0.0,1.0,15.663751,5.653462,0.097246

In [104]:
print("Number of rows:", len(msoa_features))
print("Number of MSOAs:", msoa_features["MSOA21CD"].nunique())

print("\nDuplicate MSOAs:")
print(msoa_features["MSOA21CD"].duplicated().sum())

print("\nMissing values:")
print(msoa_features.isnull().sum())

Number of rows: 27
Number of MSOAs: 27

Duplicate MSOAs:
0

Missing values:
MSOA21CD                                            0
MSOA21NM                                            0
MSOA GVA Estimates (millions)                       5
Working_Age_Pop                                     0
Total_Pop_Mid2024                                   0
part_time_employees                                 0
full_time_employees                                 0
total_employees                                     0
bus_stop_count                                      0
area_km2                                            0
LU_large_2025_msoa                                  0
LU_medium_2025_msoa                                 0
LU_micro_2025_msoa                                  0
LU_small_2025_msoa                                  0
LU_total_2025_msoa                                  0
LU_pct_micro_2025_msoa                              0
LU_pct_small_2025_msoa                              0
LU_pct_medium_2025_msoa                             0
LU_pct_large_2025_msoa                              0
LU_diversity_1-HHI_2025                             0
pct_enterprise_0_to_49_thousand_2025_msoa           0
pct_enterprise_100_to_249_thousand_2025_msoa        0
pct_enterprise_1000_to_1999_thousand_2025_msoa      0
pct_enterprise_10000_to_49999_thousand_2025_msoa    0
pct_enterprise_2000_to_4999_thousand_2025_msoa      0
pct_enterprise_250_to_499_thousand_2025_msoa        0
pct_enterprise_50_to_99_thousand_2025_msoa          0
pct_enterprise_500_to_999_thousand_2025_msoa        0
pct_enterprise_5000_to_9999_thousand_2025_msoa      0
pct_enterprise_50000plus_thousand_2025_msoa         0
turnover_diversity_1-HHI_2025_msoa                  0
total_enterprises_2025_msoa                         0
share_enterprises_creative_2025_msoa                0
share_enterprises_foundational_2025_msoa            0
share_enterprises_green_aligned_2025_msoa           0
share_enterprises_industrial_2025_msoa              0
share_enterprises_kibs_2025_msoa                    0
share_enterprises_anchor_2025_msoa                  0
share_enterprises_public_2025_msoa                  0
share_enterprises_private_2025_msoa                 0
enterprises_per_1k_residents_2025                   0
bus_stop_density                                    0
employment_rate_per_pop                             0
dtype: int64

In [105]:
import numpy as np
print(np.isinf(msoa_features.select_dtypes(include="number")).sum())

MSOA GVA Estimates (millions)                       0
Working_Age_Pop                                     0
Total_Pop_Mid2024                                   0
part_time_employees                                 0
full_time_employees                                 0
total_employees                                     0
bus_stop_count                                      0
area_km2                                            0
LU_large_2025_msoa                                  0
LU_medium_2025_msoa                                 0
LU_micro_2025_msoa                                  0
LU_small_2025_msoa                                  0
LU_total_2025_msoa                                  0
LU_pct_micro_2025_msoa                              0
LU_pct_small_2025_msoa                              0
LU_pct_medium_2025_msoa                             0
LU_pct_large_2025_msoa                              0
LU_diversity_1-HHI_2025                             0
pct_enterprise_0_to_49_thousand_2025_msoa           0
pct_enterprise_100_to_249_thousand_2025_msoa        0
pct_enterprise_1000_to_1999_thousand_2025_msoa      0
pct_enterprise_10000_to_49999_thousand_2025_msoa    0
pct_enterprise_2000_to_4999_thousand_2025_msoa      0
pct_enterprise_250_to_499_thousand_2025_msoa        0
pct_enterprise_50_to_99_thousand_2025_msoa          0
pct_enterprise_500_to_999_thousand_2025_msoa        0
pct_enterprise_5000_to_9999_thousand_2025_msoa      0
pct_enterprise_50000plus_thousand_2025_msoa         0
turnover_diversity_1-HHI_2025_msoa                  0
total_enterprises_2025_msoa                         0
share_enterprises_creative_2025_msoa                0
share_enterprises_foundational_2025_msoa            0
share_enterprises_green_aligned_2025_msoa           0
share_enterprises_industrial_2025_msoa              0
share_enterprises_kibs_2025_msoa                    0
share_enterprises_anchor_2025_msoa                  0
share_enterprises_public_2025_msoa                  0
share_enterprises_private_2025_msoa                 0
enterprises_per_1k_residents_2025                   0
bus_stop_density                                    0
employment_rate_per_pop                             0
dtype: int64

In [106]:
employment_check = df_swindon[
    [
        "MSOA21CD",
        "LSOA21CD",
        "total_employees",
        "Working_Age_Pop",
        "Total_Pop_Mid2024",
        "employment_rate_per_pop"
    ]
]

display(employment_check.head(10))

,MSOA21CD,LSOA21CD,total_employees,Working_Age_Pop,Total_Pop_Mid2024,employment_rate_per_pop
0,E02006849,E01015471,80,1519,2276,0.035149
1,E02003219,E01015473,10250,1334,2177,4.708314
2,E02003226,E01015475,1750,1778,2494,0.701684
3,E02003226,E01015477,250,1288,1809,0.138198
4,E02003232,E01015478,450,1132,1627,0.276583
5,E02003228,E01015479,2250,1711,2476,0.908724
6,E02003226,E01015480,225,2259,2997,0.075075
7,E02003224,E01015481,300,1136,1746,0.171821
8,E02003224,E01015482,420,788,1271,0.330448
9,E02003224,E01015483,75,783,1367,0.054865

In [107]:
check_total_pop = (
    df_swindon["total_employees"]
    / df_swindon["Total_Pop_Mid2024"]
)

check_working_age = (
    df_swindon["total_employees"]
    / df_swindon["Working_Age_Pop"]
)

print("Using total population:")
print(check_total_pop.head(10))

print("\nUsing working age population:")
print(check_working_age.head(10))

print("\nOriginal employment rate:")
print(df_swindon["employment_rate_per_pop"].head(10))

Using total population:
0    0.035149
1    4.708314
2    0.701684
3    0.138198
4    0.276583
5    0.908724
6    0.075075
7    0.171821
8    0.330448
9    0.054865
dtype: float64

Using working age population:
0    0.052666
1    7.683658
2    0.984252
3    0.194099
4    0.397527
5    1.315020
6    0.099602
7    0.264085
8    0.532995
9    0.095785
dtype: float64

Original employment rate:
0    0.035149
1    4.708314
2    0.701684
3    0.138198
4    0.276583
5    0.908724
6    0.075075
7    0.171821
8    0.330448
9    0.054865
Name: employment_rate_per_pop, dtype: float64

In [108]:
msoa_features.to_csv("../data/msoa_features.csv",index=False)
print(msoa_features.shape)

(27, 43)